# Adding sample values for the variables. DB is not used by me anyway. So adding the real values here.
DB_HOST = "ep-frosty-cloud-a507w5i6.us-east-2.aws.neon.tech"
DB_PORT = "5432"
DB_NAME = "hackathon"
DB_USER = "hackathon_owner"
DB_PASSWORD = "BmvXI4b2MUEY"

# You can get api key from together.ai
TOGETHER_API_KEY = "xxxxxxx"